services:
  db:
    image: postgres:latest
    container_name: postgres_news_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_service
    ports:
      - "5432:5432"
    volumes:
      - db_news_service:/var/lib/postgresql/data

volumes:
  db_news_service:
